tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

image: sdshmctspublic.azurecr.io/mi/adf-integration-runtime

replicaCount: 2

appName: mi-adf-shir
namespace: mi

keyVaultName: mi-vault
keyVaultSecrets:
  - mi-adf-auth-key

authKeySecretName: mi-adf-auth
secretsMountPath: 'C:\kvmnt'

shirNodeName: ''
haEnabled: "true"
haPort: "8060"

memoryRequests: '2048Mi'
memoryLimits: '2048Mi'
cpuRequests: '500m'

injectDynatrace: "false"
