{{- $serviceAccount := lookup "v1" "ServiceAccount" .Values.namespace .Values.namespace }}
{{- $saClientId := index $serviceAccount.metadata.annotations "azure.workload.identity/client-id" }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.appName }}-secret-provider
spec:
  provider: azure
  parameters:
    clientID: {{ $saClientId }}
    keyvaultName: {{ .Values.keyVaultName }}-{{ .Values.environment }}
    objects: |
        array:
      {{- range $secret := .Values.keyVaultSecrets }}       
          - |
            objectName: {{ $secret }}
            objectType: secret
            objectVersion: ""
      {{- end }}
    resourceGroup: {{ .Values.resourceGroup }}
    subscriptionId: {{ .Values.subscriptionId }}
    tenantId: {{ .Values.tenantId }}
